In [2]:
import numpy as np

In [3]:
[1, 4, 2, 5]

[1, 4, 2, 5]

In [4]:
np.array([1, 4, 2, 5])

array([1, 4, 2, 5])

In [5]:
np.array([1, 4, 2.5, 5])

array([1. , 4. , 2.5, 5. ])

In [6]:
np.array([1, 4, 2.5, 5], dtype='int')

array([1, 4, 2, 5])

In [7]:
np.array([1, 'a', 2.5])

array(['1', 'a', '2.5'], dtype='<U11')

In [8]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.zeros(10, dtype='str')

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [10]:
np.zeros((2,3), dtype='int')

array([[0, 0, 0],
       [0, 0, 0]])

In [11]:
np.ones((3,2),dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [12]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [13]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
np.arange(100, 0, -1)

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2,   1])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random(10)

array([0.83376565, 0.53388959, 0.20073147, 0.11841823, 0.63905433,
       0.06972988, 0.94774309, 0.74465097, 0.83714737, 0.78536928])

In [18]:
np.random.random((3,3))

array([[0.51087177, 0.58141456, 0.25609529],
       [0.17921757, 0.85642786, 0.23583981],
       [0.53292891, 0.26469285, 0.09141685]])

In [19]:
np.random.normal(10000, 2000, 10)

array([11879.92415232, 12335.1539723 ,  8489.74418138, 11064.05419428,
        4604.97934969,  9706.35340856,  8608.56168337,  8487.55908865,
       12004.15866459,  7753.34597521])

In [20]:
np.random.normal(10000, 2000, (3,3))

array([[10019.01997891,  7955.11115941, 12859.62794236],
       [12468.22876522, 13116.93615473, 10680.44531225],
       [10349.4340952 ,  7630.1609233 , 11219.93652028]])

In [21]:
np.random.normal(0, 1, 10)

array([-0.75996158, -0.12756857,  0.46866582, -0.60711193,  0.10175248,
        0.17404686, -0.20237061, -1.28185771,  0.77699329, -0.39743912])

In [22]:
np.random.randint(1, 37, (5,6))

array([[33, 25, 29, 18, 19, 32],
       [33,  6,  7, 21,  7, 31],
       [17,  7, 25,  5, 19, 26],
       [17, 31,  3, 35, 15, 27],
       [31, 23, 21, 14, 20, 19]])

In [23]:
x = np.arange(1,11)
y = np.arange(11,21)

In [24]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
x+y

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [27]:
np.add(x,y)

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [28]:
np.add(x, 2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
x - y

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [30]:
x / y

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [31]:
np.abs(x - y)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [33]:
np.exp2(x)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [34]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
y

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
np.power(y, x)

array([         11,         144,        2197,       38416,      759375,
          16777216,   410338673, -1864941312,   565150579,   797966336],
      dtype=int32)

In [37]:
np.power(3, x)

array([    3,     9,    27,    81,   243,   729,  2187,  6561, 19683,
       59049], dtype=int32)

In [38]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [39]:
x = np.array([70,80,100,90,80], dtype='int64')

In [40]:
x.sum()

420

In [41]:
np.sum(x)

420

In [42]:
x.mean()

84.0

In [43]:
np.mean(x)

84.0

In [44]:
np.prod(x)

4032000000

In [45]:
np.max(x)

100

In [46]:
x


array([ 70,  80, 100,  90,  80], dtype=int64)

In [48]:
np.argmax(x)

2

In [49]:
x[np.argmax(x)]

100

In [50]:
np.median(x)

80.0